//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongViec()
        {
            this.TinTuyenDungs = new HashSet<TinTuyenDung>();
            this.UngTuyens = new HashSet<UngTuyen>();
        }
    
        public int ID_CV { get; set; }
        public string TenCV { get; set; }
        public string MoTaCV { get; set; }
        public string LoaiViec { get; set; }
        public Nullable<int> ID_NN { get; set; }
        public Nullable<int> ID_Admin { get; set; }
        public Nullable<int> ID_NTD { get; set; }
        public Nullable<int> ID_DD { get; set; }
        public Nullable<int> ID_LV { get; set; }
    
        public virtual ND_Admin ND_Admin { get; set; }
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual LinhVuc LinhVuc { get; set; }
        public virtual NganhNghe NganhNghe { get; set; }
        public virtual NhaTuyenDung NhaTuyenDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinTuyenDung> TinTuyenDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UngTuyen> UngTuyens { get; set; }
    }
}
