//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinhVuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinhVuc()
        {
            this.CongViecs = new HashSet<CongViec>();
            this.NganhNghes = new HashSet<NganhNghe>();
            this.TinUngTuyens = new HashSet<TinUngTuyen>();
            this.NhaTuyenDungs = new HashSet<NhaTuyenDung>();
        }
    
        public int ID_LV { get; set; }
        public string TenLV { get; set; }
        public string MotaLV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NganhNghe> NganhNghes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinUngTuyen> TinUngTuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhaTuyenDung> NhaTuyenDungs { get; set; }

        public ICollection<Thuoc> Thuocs { get; internal set; }
    }
}
