//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ND_Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ND_Admin()
        {
            this.CongViecs = new HashSet<CongViec>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
            this.TinTuyenDungs = new HashSet<TinTuyenDung>();
            this.TinUngTuyens = new HashSet<TinUngTuyen>();
        }
    
        public int ID_Admin { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public System.DateTime DOB { get; set; }
        public string GioiTinh { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> TgLamViec { get; set; }
        public Nullable<int> ID_TK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinTuyenDung> TinTuyenDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinUngTuyen> TinUngTuyens { get; set; }
    }
}
