//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTuyenDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaTuyenDung()
        {
            this.CongViecs = new HashSet<CongViec>();
            this.TinTuyenDungs = new HashSet<TinTuyenDung>();
            this.DiaDiems = new HashSet<DiaDiem>();
            this.LinhVucs = new HashSet<LinhVuc>();
            this.UngViens = new HashSet<UngVien>();
        }
    
        public int ID_NTD { get; set; }
        public string TenNTD { get; set; }
        public string QuocGia { get; set; }
        public string QuyMo { get; set; }
        public string GPKD { get; set; }
        public Nullable<int> ID_TK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinTuyenDung> TinTuyenDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaDiem> DiaDiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinhVuc> LinhVucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UngVien> UngViens { get; set; }
        public ICollection<O> Os { get; internal set; }

        public ICollection<Thuoc> Thuocs { get; internal set; }

        public ICollection<Tim> Tims { get; internal set; }
    }
}
