//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTDEntities : DbContext
    {
        public QLTDEntities()
            : base("name=QLTDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CongViec> CongViecs { get; set; }
        public virtual DbSet<DiaDiem> DiaDiems { get; set; }
        public virtual DbSet<LinhVuc> LinhVucs { get; set; }
        public virtual DbSet<ND_Admin> ND_Admin { get; set; }
        public virtual DbSet<NganhNghe> NganhNghes { get; set; }
        public virtual DbSet<NhaTuyenDung> NhaTuyenDungs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TinTuyenDung> TinTuyenDungs { get; set; }
        public virtual DbSet<TinUngTuyen> TinUngTuyens { get; set; }
        public virtual DbSet<UngTuyen> UngTuyens { get; set; }
        public virtual DbSet<UngVien> UngViens { get; set; }
    }
}
