//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UngTuyen
    {
        public int ID_CV { get; set; }
        public int ID_UV { get; set; }
        public string TrangThaiUT { get; set; }
        public System.DateTime TgianCapNhatTT { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual UngVien UngVien { get; set; }
    }
}
