//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UngVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UngVien()
        {
            this.TinUngTuyens = new HashSet<TinUngTuyen>();
            this.UngTuyens = new HashSet<UngTuyen>();
            this.NhaTuyenDungs = new HashSet<NhaTuyenDung>();
        }
    
        public int ID_UV { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public System.DateTime DOB { get; set; }
        public string GioiTinh { get; set; }
        public string Email { get; set; }
        public string SYLL { get; set; }
        public string CV { get; set; }
        public Nullable<int> ID_DD { get; set; }
        public Nullable<int> ID_TK { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinUngTuyen> TinUngTuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UngTuyen> UngTuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhaTuyenDung> NhaTuyenDungs { get; set; }

        public ICollection<Tim> Tims { get; internal set; }
    }
}
